Feat: testing class added
jeonjw95/Invaders pull request #55
Opened 2023-12-05 13:10 UTC by oh0227

게임 스크린에서 기본적으로 일어나는 상황들에 대한 테스트 코드 작성

2023-12-05 23:50 UTC, choeun01 approved these changes
확인했습니다. 고생하셨습니다.

2023-12-06 00:18 UTC, jeonjw95 requested changes

2023-12-06 00:18 UTC, jeonjw95 commented on src/engine/DrawManager.java
> +		if(frame != null) graphics = frame.getGraphics();
해당 라인이 변경된 이유가 궁금합니다

2023-12-06 00:18 UTC, jeonjw95 commented on src/test/java/screen/GameScreenTest.java
> +        fail("루프가 10초 이상 실행됨"); // 테스트 실패로 처리하거나 다른 적절한 조치를 취할 수 있습니다.
10초 이상 실행됐다는 것이 이 테스트의 실패와 연관이 없는 것 같습니다. 무한루프를 방지하고 테스트 시간을 줄일 수 있는 방법을 모색하면 좋을 것 같습니다.

2023-12-06 00:18 UTC, jeonjw95 commented on src/test/java/screen/GameScreenTest.java
> +        fail("루프가 10초 이상 실행됨"); // 테스트 실패로 처리하거나 다른 적절한 조치를 취할 수 있습니다.
위 리뷰와 동일합니다

2023-12-06 04:18 UTC, msk226 approved these changes

2023-12-06 04:18 UTC, msk226 commented on src/test/java/screen/GameScreenTest.java
> +        fail("루프가 10초 이상 실행됨"); // 테스트 실패로 처리하거나 다른 적절한 조치를 취할 수 있습니다.
주석에 있는 설명에는 15초 이상 실행하면 강제 종료한다고 되어있는데, 지금 코드 상에는 "10초 이상 실행 됨" 이라고 나와있어서 모호한 것 같습니다.

2023-12-06 05:55 UTC, oh0227 commented on src/engine/DrawManager.java
> +		if(frame != null) graphics = frame.getGraphics();
게임스크린을 테스트할 때는 화면에 창을 띄울 필요 없이 테스트만 진행하기 위해서 추가한 코드입니다.

2023-12-06 13:42 UTC, ssxrxbx approved these changes
팀원 분들의 리뷰 말고는 이의 없습니다. 고생하셨습니다!

2023-12-06 13:45 UTC, jeonjw95 commented on src/engine/DrawManager.java
> +		if(frame != null) graphics = frame.getGraphics();
실제 게임에는 영향이 없는건가요?

2023-12-06 16:22 UTC, oh0227 commented on src/engine/DrawManager.java
> +		if(frame != null) graphics = frame.getGraphics();
네 실제 게임에는 영향 없습니다!

2023-12-06 16:22 UTC, oznwoo commented on src/test/java/screen/GameScreenTest.java
> +        fail("루프가 10초 이상 실행됨"); // 테스트 실패로 처리하거나 다른 적절한 조치를 취할 수 있습니다.
새로 commit한 내용에 수정했습니다!

2023-12-06 16:22 UTC, oh0227 commented on src/test/java/screen/GameScreenTest.java
> +        fail("루프가 10초 이상 실행됨"); // 테스트 실패로 처리하거나 다른 적절한 조치를 취할 수 있습니다.
새로 commit한 내용에 수정했습니다!

2023-12-07 13:30 UTC, jeonjw95 requested changes

2023-12-07 13:30 UTC, jeonjw95 commented on src/test/java/screen/GameScreenTest.java
> +    private static boolean test0() {return test0;}
static이 필요한 코드인가요? 필요하다면 public으로 변경하고 필요없다면 static을 제거 바랍니다

2023-12-07 13:46 UTC, jeonjw95 requested changes
gradle build 문제가 발생합니다. 해결바랍니다!

error: package org.junit.jupiter.api does not exist import static org.junit.jupiter.api.Assertions.*;

2023-12-07 17:33 UTC, oh0227 commented on src/test/java/screen/GameScreenTest.java
> +    private static boolean test0() {return test0;}
없어도 큰 지장이 없는 코드라 새 commit에서 삭제했습니다!

2023-12-07 17:52 UTC, oh0227 commented
> gradle build 문제가 발생합니다. 해결바랍니다!
> 
> error: package org.junit.jupiter.api does not exist import static org.junit.jupiter.api.Assertions.*;

해결했습니다. 잘 되는지 확인 부탁드립니다!

2023-12-08 04:25 UTC, choeun01 approved these changes
gradle 수정 사항 확인했습니다. 고생많으셨습니다.

2023-12-08 05:33 UTC, jeonjw95 approved these changes

2023-12-08 05:33 UTC, merged